export default {
  primary: '#647687',
  onPrimary: 'white',
  pressedPrimary: '#BBC7CE',
  secondary: '#8fba8f',
  onSecondary: '',
  text: 'black',
  background: '#FEFCFF',
  disabled: 'lightgrey',
  pressed: '#EBEBEB',
  error: '#D2042D',
  onError: '#FEFCFF',
  success: 'green',
  onSuccess: '#FEFCFF',
};
