export default {
  primary: '#647687',
  onPrimary: '#FEFCFF',
  pressedPrimary: '#BBC7CE',
  secondary: '#8fba8f',
  onSecondary: '',
  text: 'black',
  background: '#FEFCFF',
  disabled: '',
  pressed: '#EBEBEB',
  error: '',
  onError: '#FEFCFF',
  success: 'green',
  onSuccess: '#FEFCFF',
};
